const fs = require("fs");
const path = require("path");
const { log } = require("../utils");

exports.generateHtmlReport = generateHtmlReport;

/**
 * Generates a self-contained HTML report from test results
 * @param {Object} results - The test results object from runTests
 * @param {Object} config - The configuration object
 * @param {string} outputPath - Path where the HTML report should be saved
 * @returns {Object} Status object with result and path
 */
async function generateHtmlReport(results, config, outputPath) {
  try {
    const html = buildHtmlReport(results);
    
    // Ensure directory exists
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    
    fs.writeFileSync(outputPath, html, 'utf8');
    log(config, "info", `HTML report generated at ${outputPath}`);
    
    return {
      status: "PASS",
      description: "HTML report generated successfully",
      path: outputPath
    };
  } catch (error) {
    log(config, "error", `Failed to generate HTML report: ${error.message}`);
    return {
      status: "FAIL",
      description: `Failed to generate HTML report: ${error.message}`
    };
  }
}

/**
 * Builds the complete HTML report with embedded CSS
 * @param {Object} results - The test results object
 * @returns {string} Complete HTML document
 */
function buildHtmlReport(results) {
  const timestamp = new Date().toISOString();
  const summary = results.summary || {};
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Doc Detective Test Results</title>
  <style>
    ${getEmbeddedCss()}
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>Doc Detective Test Results</h1>
      <div class="timestamp">Generated: ${formatTimestamp(timestamp)}</div>
    </header>
    
    ${buildSummarySection(summary)}
    ${buildSpecsSection(results.specs || [])}
    
    <footer class="footer">
      <p>Generated by <a href="https://doc-detective.com" target="_blank">Doc Detective</a></p>
    </footer>
  </div>
  
  <script>
    ${getEmbeddedScript()}
  </script>
</body>
</html>`;
}

/**
 * Returns embedded CSS for styling the report
 * @returns {string} CSS styles
 */
function getEmbeddedCss() {
  return `
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #f5f5f5;
      padding: 20px;
    }
    
    .container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      overflow: hidden;
    }
    
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      text-align: center;
    }
    
    .header h1 {
      font-size: 2rem;
      margin-bottom: 10px;
    }
    
    .timestamp {
      opacity: 0.9;
      font-size: 0.9rem;
    }
    
    .summary {
      padding: 30px;
      background: #f9fafb;
      border-bottom: 2px solid #e5e7eb;
    }
    
    .summary h2 {
      margin-bottom: 20px;
      color: #374151;
    }
    
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
      margin-bottom: 20px;
    }
    
    .summary-card {
      background: white;
      padding: 20px;
      border-radius: 8px;
      border-left: 4px solid #ccc;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    
    .summary-card h3 {
      font-size: 0.875rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #6b7280;
      margin-bottom: 10px;
    }
    
    .stat-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 8px 0;
      border-bottom: 1px solid #f3f4f6;
    }
    
    .stat-row:last-child {
      border-bottom: none;
    }
    
    .stat-label {
      font-weight: 500;
      text-transform: capitalize;
    }
    
    .stat-value {
      font-size: 1.25rem;
      font-weight: 600;
    }
    
    .badge {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 12px;
      font-size: 0.875rem;
      font-weight: 600;
      text-transform: uppercase;
    }
    
    .badge-pass {
      background: #d1fae5;
      color: #065f46;
    }
    
    .badge-fail {
      background: #fee2e2;
      color: #991b1b;
    }
    
    .badge-warning {
      background: #fef3c7;
      color: #92400e;
    }
    
    .badge-skipped {
      background: #e5e7eb;
      color: #4b5563;
    }
    
    .specs-section {
      padding: 30px;
    }
    
    .specs-section h2 {
      margin-bottom: 20px;
      color: #374151;
    }
    
    .spec {
      margin-bottom: 20px;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      overflow: hidden;
    }
    
    .spec-header {
      background: #f9fafb;
      padding: 15px 20px;
      cursor: pointer;
      display: flex;
      justify-content: space-between;
      align-items: center;
      transition: background 0.2s;
    }
    
    .spec-header:hover {
      background: #f3f4f6;
    }
    
    .spec-title {
      display: flex;
      align-items: center;
      gap: 12px;
      flex: 1;
    }
    
    .spec-title h3 {
      font-size: 1.1rem;
      color: #1f2937;
      margin: 0;
    }
    
    .expand-icon {
      transition: transform 0.2s;
      font-size: 1.2rem;
      color: #6b7280;
    }
    
    .spec.expanded .expand-icon {
      transform: rotate(90deg);
    }
    
    .spec-content {
      display: none;
      padding: 20px;
      background: white;
    }
    
    .spec.expanded .spec-content {
      display: block;
    }
    
    .spec-info {
      margin-bottom: 15px;
      padding: 10px;
      background: #f9fafb;
      border-radius: 4px;
      font-size: 0.9rem;
      color: #6b7280;
    }
    
    .test {
      margin-bottom: 15px;
      border: 1px solid #e5e7eb;
      border-radius: 6px;
      overflow: hidden;
    }
    
    .test-header {
      background: #fafafa;
      padding: 12px 15px;
      cursor: pointer;
      display: flex;
      justify-content: space-between;
      align-items: center;
      transition: background 0.2s;
    }
    
    .test-header:hover {
      background: #f5f5f5;
    }
    
    .test-title {
      display: flex;
      align-items: center;
      gap: 10px;
      flex: 1;
    }
    
    .test-title h4 {
      font-size: 1rem;
      color: #374151;
      margin: 0;
    }
    
    .test.expanded .expand-icon {
      transform: rotate(90deg);
    }
    
    .test-content {
      display: none;
      padding: 15px;
      background: white;
    }
    
    .test.expanded .test-content {
      display: block;
    }
    
    .test-info {
      margin-bottom: 12px;
      font-size: 0.875rem;
      color: #6b7280;
    }
    
    .context {
      margin-bottom: 12px;
      border: 1px solid #e5e7eb;
      border-radius: 4px;
      overflow: hidden;
    }
    
    .context-header {
      background: #f9fafb;
      padding: 10px 12px;
      cursor: pointer;
      display: flex;
      justify-content: space-between;
      align-items: center;
      transition: background 0.2s;
    }
    
    .context-header:hover {
      background: #f5f5f5;
    }
    
    .context-title {
      display: flex;
      align-items: center;
      gap: 8px;
      flex: 1;
      font-size: 0.9rem;
      font-weight: 500;
    }
    
    .context.expanded .expand-icon {
      transform: rotate(90deg);
    }
    
    .context-content {
      display: none;
      padding: 12px;
      background: white;
    }
    
    .context.expanded .context-content {
      display: block;
    }
    
    .steps {
      margin-top: 10px;
    }
    
    .step {
      padding: 10px;
      margin-bottom: 8px;
      border-left: 3px solid #ccc;
      background: #fafafa;
      border-radius: 4px;
    }
    
    .step-pass {
      border-left-color: #10b981;
      background: #f0fdf4;
    }
    
    .step-fail {
      border-left-color: #ef4444;
      background: #fef2f2;
    }
    
    .step-warning {
      border-left-color: #f59e0b;
      background: #fffbeb;
    }
    
    .step-skipped {
      border-left-color: #9ca3af;
      background: #f9fafb;
    }
    
    .step-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 5px;
    }
    
    .step-action {
      font-weight: 600;
      font-size: 0.9rem;
      color: #1f2937;
    }
    
    .step-description {
      font-size: 0.875rem;
      color: #4b5563;
      margin-top: 5px;
    }
    
    .step-details {
      margin-top: 8px;
      font-size: 0.8rem;
      color: #6b7280;
      background: white;
      padding: 8px;
      border-radius: 4px;
      font-family: 'Monaco', 'Courier New', monospace;
      white-space: pre-wrap;
      word-break: break-word;
    }
    
    .footer {
      background: #f9fafb;
      padding: 20px;
      text-align: center;
      color: #6b7280;
      border-top: 1px solid #e5e7eb;
    }
    
    .footer a {
      color: #667eea;
      text-decoration: none;
    }
    
    .footer a:hover {
      text-decoration: underline;
    }
    
    @media (max-width: 768px) {
      .summary-grid {
        grid-template-columns: 1fr;
      }
      
      .header h1 {
        font-size: 1.5rem;
      }
    }
  `;
}

/**
 * Returns embedded JavaScript for interactive features
 * @returns {string} JavaScript code
 */
function getEmbeddedScript() {
  return `
    function toggleSection(element) {
      element.classList.toggle('expanded');
    }
    
    // Add click handlers to all expandable sections
    document.addEventListener('DOMContentLoaded', function() {
      // Expand first spec by default
      const firstSpec = document.querySelector('.spec');
      if (firstSpec) {
        firstSpec.classList.add('expanded');
      }
      
      // Add click handlers
      document.querySelectorAll('.spec-header').forEach(header => {
        header.addEventListener('click', function() {
          toggleSection(this.parentElement);
        });
      });
      
      document.querySelectorAll('.test-header').forEach(header => {
        header.addEventListener('click', function() {
          toggleSection(this.parentElement);
        });
      });
      
      document.querySelectorAll('.context-header').forEach(header => {
        header.addEventListener('click', function() {
          toggleSection(this.parentElement);
        });
      });
    });
  `;
}

/**
 * Formats a timestamp for display
 * @param {string} timestamp - ISO timestamp
 * @returns {string} Formatted timestamp
 */
function formatTimestamp(timestamp) {
  const date = new Date(timestamp);
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  });
}

/**
 * Builds the summary section HTML
 * @param {Object} summary - Summary object from results
 * @returns {string} HTML string
 */
function buildSummarySection(summary) {
  const sections = ['specs', 'tests', 'contexts', 'steps'];
  
  return `
    <section class="summary">
      <h2>Test Summary</h2>
      <div class="summary-grid">
        ${sections.map(section => {
          const data = summary[section] || { pass: 0, fail: 0, warning: 0, skipped: 0 };
          const total = (data.pass || 0) + (data.fail || 0) + (data.warning || 0) + (data.skipped || 0);
          return `
            <div class="summary-card">
              <h3>${section}</h3>
              ${buildStatRow('Pass', data.pass || 0, 'pass')}
              ${buildStatRow('Fail', data.fail || 0, 'fail')}
              ${buildStatRow('Warning', data.warning || 0, 'warning')}
              ${buildStatRow('Skipped', data.skipped || 0, 'skipped')}
              <div class="stat-row" style="margin-top: 10px; font-weight: bold;">
                <span class="stat-label">Total</span>
                <span class="stat-value">${total}</span>
              </div>
            </div>
          `;
        }).join('')}
      </div>
    </section>
  `;
}

/**
 * Builds a stat row for the summary section
 * @param {string} label - Label for the stat
 * @param {number} value - Value of the stat
 * @param {string} type - Type (pass, fail, warning, skipped)
 * @returns {string} HTML string
 */
function buildStatRow(label, value, type) {
  return `
    <div class="stat-row">
      <span class="stat-label">${label}</span>
      <span class="stat-value badge badge-${type}">${value}</span>
    </div>
  `;
}

/**
 * Builds the specs section HTML
 * @param {Array} specs - Array of spec objects
 * @returns {string} HTML string
 */
function buildSpecsSection(specs) {
  if (!specs || specs.length === 0) {
    return `
      <section class="specs-section">
        <h2>Test Specifications</h2>
        <p>No test specifications found.</p>
      </section>
    `;
  }
  
  return `
    <section class="specs-section">
      <h2>Test Specifications</h2>
      ${specs.map(spec => buildSpec(spec)).join('')}
    </section>
  `;
}

/**
 * Builds HTML for a single spec
 * @param {Object} spec - Spec object
 * @returns {string} HTML string
 */
function buildSpec(spec) {
  const result = spec.result || 'SKIPPED';
  const badge = `<span class="badge badge-${result.toLowerCase()}">${result}</span>`;
  
  return `
    <div class="spec">
      <div class="spec-header">
        <div class="spec-title">
          <span class="expand-icon">▶</span>
          <h3>${escapeHtml(spec.description || spec.specId)}</h3>
        </div>
        ${badge}
      </div>
      <div class="spec-content">
        <div class="spec-info">
          <strong>Spec ID:</strong> ${escapeHtml(spec.specId)}<br>
          ${spec.contentPath ? `<strong>Path:</strong> ${escapeHtml(spec.contentPath)}<br>` : ''}
        </div>
        ${buildTests(spec.tests || [])}
      </div>
    </div>
  `;
}

/**
 * Builds HTML for tests
 * @param {Array} tests - Array of test objects
 * @returns {string} HTML string
 */
function buildTests(tests) {
  if (!tests || tests.length === 0) {
    return '<p>No tests found in this specification.</p>';
  }
  
  return tests.map(test => buildTest(test)).join('');
}

/**
 * Builds HTML for a single test
 * @param {Object} test - Test object
 * @returns {string} HTML string
 */
function buildTest(test) {
  const result = test.result || 'SKIPPED';
  const badge = `<span class="badge badge-${result.toLowerCase()}">${result}</span>`;
  
  return `
    <div class="test">
      <div class="test-header">
        <div class="test-title">
          <span class="expand-icon">▶</span>
          <h4>${escapeHtml(test.description || test.testId)}</h4>
        </div>
        ${badge}
      </div>
      <div class="test-content">
        <div class="test-info">
          <strong>Test ID:</strong> ${escapeHtml(test.testId)}<br>
          ${test.contentPath ? `<strong>Path:</strong> ${escapeHtml(test.contentPath)}<br>` : ''}
          ${test.detectSteps !== undefined ? `<strong>Detect Steps:</strong> ${test.detectSteps}<br>` : ''}
        </div>
        ${buildContexts(test.contexts || [])}
      </div>
    </div>
  `;
}

/**
 * Builds HTML for contexts
 * @param {Array} contexts - Array of context objects
 * @returns {string} HTML string
 */
function buildContexts(contexts) {
  if (!contexts || contexts.length === 0) {
    return '<p>No contexts found in this test.</p>';
  }
  
  return contexts.map(context => buildContext(context)).join('');
}

/**
 * Builds HTML for a single context
 * @param {Object} context - Context object
 * @returns {string} HTML string
 */
function buildContext(context) {
  const result = context.result || 'SKIPPED';
  const badge = `<span class="badge badge-${result.toLowerCase()}">${result}</span>`;
  const platform = context.platform ? escapeHtml(context.platform) : 'N/A';
  const browser = context.browser ? escapeHtml(context.browser) : 'N/A';
  
  return `
    <div class="context">
      <div class="context-header">
        <div class="context-title">
          <span class="expand-icon">▶</span>
          <span>Platform: ${platform} | Browser: ${browser}</span>
        </div>
        ${badge}
      </div>
      <div class="context-content">
        ${buildSteps(context.steps || [])}
      </div>
    </div>
  `;
}

/**
 * Builds HTML for steps
 * @param {Array} steps - Array of step objects
 * @returns {string} HTML string
 */
function buildSteps(steps) {
  if (!steps || steps.length === 0) {
    return '<p>No steps found in this context.</p>';
  }
  
  return `
    <div class="steps">
      ${steps.map((step, index) => buildStep(step, index)).join('')}
    </div>
  `;
}

/**
 * Builds HTML for a single step
 * @param {Object} step - Step object
 * @param {number} index - Step index
 * @returns {string} HTML string
 */
function buildStep(step, index) {
  const result = step.result || 'SKIPPED';
  const badge = `<span class="badge badge-${result.toLowerCase()}">${result}</span>`;
  
  // Determine the action type
  let action = 'Unknown';
  const stepKeys = Object.keys(step).filter(key => !['result', 'description', 'outputs'].includes(key));
  if (stepKeys.length > 0) {
    action = stepKeys[0];
  }
  
  return `
    <div class="step step-${result.toLowerCase()}">
      <div class="step-header">
        <span class="step-action">Step ${index + 1}: ${escapeHtml(action)}</span>
        ${badge}
      </div>
      ${step.description ? `<div class="step-description">${escapeHtml(step.description)}</div>` : ''}
      ${step.outputs ? `<div class="step-details">${escapeHtml(JSON.stringify(step.outputs, null, 2))}</div>` : ''}
    </div>
  `;
}

/**
 * Escapes HTML special characters
 * @param {string} text - Text to escape
 * @returns {string} Escaped text
 */
function escapeHtml(text) {
  if (typeof text !== 'string') {
    return String(text);
  }
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, m => map[m]);
}
